#!/bin/bash
dataGraph = "data\data\\$1"
./GSI.exe $dataGraph "data\query\_2_road2.g" 
./GSI.exe $dataGraph "data\query\_3_road3.g" 
./GSI.exe $dataGraph "data\query\_3_triangle.g"
./GSI.exe $dataGraph "data\query\_4_road4.g"
./GSI.exe $dataGraph "data\query\_4_roadY.g"
./GSI.exe $dataGraph "data\query\_4_square.g"
./GSI.exe $dataGraph "data\query\_5_road5.g"
./GSI.exe $dataGraph "data\query\_5_plus.g"